version: '2'

services:
  ubuntu:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./home:/home
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["sh", "/home/install_commands.sh"]

###################
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin-admin
      - MINIO_ROOT_PASSWORD=admin-admin
  
  
  ##############
  
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=3.8
      - PYSPARK_DRIVER_PYTHON=3.8    
      - MINIO_ACCESSKEY=oy9WWsyFNw4lFX3P 
      - MINIO_SECRETKEY=ZQf5hwB9BYsN0fLjSTOlpZ560uXrZHZD
    ports:
      - '4040:8080'
      - '7077:7077'

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=3.8
      - PYSPARK_DRIVER_PYTHON=3.8      
    depends_on:
      - spark