version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=3.8
      - PYSPARK_DRIVER_PYTHON=3.8    
      - MINIO_ACCESSKEY=oy9WWsyFNw4lFX3P 
      - MINIO_SECRETKEY=ZQf5hwB9BYsN0fLjSTOlpZ560uXrZHZD
    ports:
      - '4040:8080'
      - '7077:7077'
    networks:
      - spark_project_network


  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=3.8
      - PYSPARK_DRIVER_PYTHON=3.8      
    depends_on:
      - spark
    networks:
      - spark_project_network

  # spark-worker2:
  #   image: docker.io/bitnami/spark:3.0.0
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - PYSPARK_PYTHON=3.8
  #     - PYSPARK_DRIVER_PYTHON=3.8      
  #   depends_on:
  #     - spark
  #   networks:
  #     - spark_project_network


networks:
  spark_project_network:
    name: spark_project_network
    external: true